### ISSUE TITLE
Content Component is not assignable to type 'FormComponent<{}, unknown>'

### ISSUE THREAD

**Issue by bobodrone** [fab4m-forms/fab4m#47]
When adding a content component that is not within a group it give this ts error:

S2322: Type 'FormComponent<unknown, any>' is not assignable to type 'FormComponent<{}, unknown>'.   The types of 'widget.type.widget' are incompatible between these types.

**Comment by fabsor** [comment]
Could you provide an example that doesn't work? I've tried to reproduce this with the following example form, using the default tsconfig provided with the vite react-ts template and it doesn't give any errors:

```tsx
const form = createForm({
  test: content({}, () => <div>My form</div>),
});

```

**Comment by fabsor** [comment]
This should be resolved now.
